### ISSUE TITLE
Unable to install v1.6.31

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/ExtensionUpdater#5]
I just tried to install v1.6.31 and got the following errors

**VS 2013**
> This extension is not supported on the current product.

**VS 2015**
```xml
<entry>
  <record>96</record>
  <time>2015/02/05 00:09:53.621</time>
  <type>Error</type>
  <source>VisualStudio</source>
  <description>End package load [ExtensionUpdaterPackage]</description>
  <guid>{CB8900A0-79FB-4C76-A6D6-F4E88D3384D2}</guid>
  <hr>80004002 - E_NOINTERFACE</hr>
  <errorinfo>Unable to cast object of type 'Microsoft.VisualStudio.ExtensionManager.ExtensionRepositoryService' to type 'Microsoft.VisualStudio.ExtensionManager.IVsExtensionRepository'.</errorinfo>
</entry>
```

**Comment by RandomlyKnighted** [comment]
I'm running into a similar problem as well. For me it says the extension cannot be installed with any version of Visual Studio that I have installed. I'm currently running Visual Studio 2013 Community Edition.

**Comment by madskristensen** [comment]
It has been fixed. This extension now only supports VS2013 since extension auto updating is built in to VS2015 RTM
