### ISSUE TITLE
VS2015 Support

### ISSUE THREAD

**Issue by MagicAndre1981** [madskristensen/ExtensionUpdater#9]
Can you please add Visual Studio 2015 support to your awesome extension or does VS2015 support it out of the box?

**Comment by madskristensen** [comment]
It's supported out of the box in 2015

**Comment by MagicAndre1981** [comment]
ok, after looking several minutes I see it in the options:

![picture](https://dl.dropboxusercontent.com/u/5749744/Bilder/Github/extension_update_VS2015.png)

But it doesn't have the option to ignore specific addons like your addon has. It would be still nice to have your better addon in VS2015.

**Comment by madskristensen** [comment]
Yes it does, but its under Tools -> Extensions and Updates...
